---
title       : ZeroMQ - Simpler Messaging to Restore Sanity
author      : Ashic Mahtab
framework   : impressjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## ZeroMQ - Simpler Messaging to Restore Sanity

### Ashic Mahtab
### @twitter | ashic@heartysoft.com | www.heartysoft.com

--- .zsl x:5000 y:5000 rot:60

## What is Messaging?

--- .zsl x:5000 y:5500 rot:60

## What are the Problems?

--- .zsl x:5000 y:6000 rot:60

## ZeroMQ?


--- .zsl x:5000 y:6500 rot:60

## ZeroMQ?

NOT Sockets, but Kinda


--- .zsl x:2000 y:6500 rot:60

## ZeroMQ

- A library for messaging and multithreading
- Cross platform
- Sockets plus awesome sauce
- Simple, reliable, scalable

--- .zsl x:5000 y:30000 rot:60

## Out of the box

- Some sockets.
- That's it.

--- .zsl x:5000 y:35000 rot:60


## Sockets

- NOT TCP sockets.
- Different types with different behaviour.
- REQ, REP, PUB, SUB, DEALER, ROUTER, PUSH, PULL, EXCLUSIVE PAIR


--- .zsl x:5000 y:-40000 rot:60


## How do you use this?

 - Put sockets together.
 - It's like lego.


--- .zsl x:5000 y:-45000 rot:60

## How do you use this?

- Build *topologies* that serve your requirements.
- Use *patterns*.


--- .zsl x:-15000 y:-45000 rot:60

## Patterns

- Simple Request Response
- Pirate Patterns (Reliable Request Response)
- PubSub
- Asynchronous
- Titanic
- more ...

--- .zsl x:-15000 y:-25000 rot:60

## Thank You

- ashic@heartysoft.com
- @ashic
- ZeroMQLondon (meetup group), @ZeroMQLondon
 
